title: Palmer Paul
description: Palmer Paul's personal website!
url: http://palmerpaul.com
permalink: /blog/:year/:month/:day/:title/
author:
  twitter: pzp1997
twitter:
  username: pzp1997
logo: /favicon.png
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
