title: Palmer Paul
description: Palmer Paul studies computer science at the University of Pennsylvania.
url: https://palmerpaul.com
permalink: /blog/:year/:month/:day/:title/
logo: /favicon.png
author:
  twitter: pzp1997
twitter:
  username: pzp1997
exclude:
  - portfolio/
collections:
  - timeline
defaults:
  -
    scope:
      path: "node_modules/"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      type: "BlogPosting"
      comments: true
      stylesheets:
        - css/blog.css
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
