title: Palmer Paul
description: Palmer Paul studies computer science at the University of Pennsylvania.
url: http://palmerpaul.com
permalink: /blog/:year/:month/:day/:title/
logo: /favicon.png
author:
  twitter: pzp1997
twitter:
  username: pzp1997
exclude:
  - portfolio/
defaults:
  -
    scope:
      path: "bower_components/"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Palmer Paul"
      comments: true
      fonts:
        - "Pacifico"
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
